# -*- coding: utf-8 -*-
"""IdadeEm2022.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fZhgdqiUmy5xDtPrOxhh5UjPLpfLb-xK

Desenvolva um programa que recebe do usuário nome completo e ano de nascimento que seja entre 1922 e 2021.
A partir dessas informações, o sistema mostrará o nome do usuário e a idade que completou, ou completará, no ano atual (2022).

Caso o usuário não digite um número ou apareça um inválido no campo do ano, o sistema informará o erro e continuará perguntando até que um valor correto seja preenchido.
"""

def idadeUsuario (ano):
  idadeAtual = 2022 - ano
  return idadeAtual

nomeCompleto = input("Informe seu nome completo: ")

while True:
  anoNascimento = input("Informe o ano do seu nascimento: ")

  if(anoNascimento.isdigit()):
    anoCerto = int(anoNascimento)

    if (anoCerto >= 1922) and (anoCerto <= 2022):
      idade = idadeUsuario(anoCerto)
      print("O usuário ", nomeCompleto, " fez ou irá fazer ", idade, " no ano de 2022")
      break
    else:
      print("Informe um ano válido entre 1922 a 2022")
  else:
    print("Informe um ano correto por favor")