# -*- coding: utf-8 -*-
"""CalculadoraZerada.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XK8M_jab_YBfz1fSUal06uLSUU9T0Dk3

Faça uma função calculadora de dois números com três parâmetros: os dois primeiros serão os números da operação e o terceiro será a entrada que definirá a operação a ser executada. Considera a seguinte definição:
1. Soma
2. Subtração
3. Multiplicação
4. Divisão

Caso seja inserido um número de operação que não exista, o resultado deverá ser 0.
"""

def calculadora(primeiroNumero, segundoNumero, operador):
  if(operador == 1):
    calculo = primeiroNumero + segundoNumero
  elif(operador == 2):
    calculo = primeiroNumero - segundoNumero
  elif(operador == 3):
    calculo = primeiroNumero * segundoNumero
  elif(operador == 4):
    calculo = primeiroNumero / segundoNumero
  else:
    calculo = 0
  return calculo

"""Apenas para separar se deu certo."""

print(calculadora(1, 2, 4))