# -*- coding: utf-8 -*-
"""CalculadoraInfinita.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1koe0fR_HIelIz-2VwM2I7f5xFwaCugff

Faça uma função calculadora que os números e as operações serão feitas pelo usuário. O código deve ficar rodando infinitamente até que o usuário escolha a opção de sair. No início, o programa mostrará a seguinte lista de operações:

1: Soma
2: Subtração
3: Multiplicação
4: Divisão
0: Sair

Digite o número para a operação correspondente e caso o usuário introduza qualquer outro, o sistema deve mostrar a mensagem “Essa opção não existe” e voltar ao menu de opções.

Após a seleção, o sistema deve pedir para o usuário inserir o primeiro e segundo valor, um de cada. Depois precisa executar a operação e mostrar o resultado na tela. Quando o usuário escolher a opção “Sair”, o sistema irá parar.

É necessário que o sistema mostre as opções sempre que finalizar uma operação e mostrar o resultado.
"""

def calculadora(num1, num2, operador):
  if(operador == 1):
    res = num1 + num2
    textoResposta = "O resulta da soma da sua operação é " + str(res)
  elif(operador == 2):
    res = num1 - num2
    textoResposta = "O resulta da subtração da sua operação é " + str(res)
  elif(operador == 3):
    res = num1 * num2
    textoResposta = "O resulta da multiplicação da sua operação é " + str(res)
  elif(operador == 4):
    res = num1 / num2
    textoResposta = "O resulta da divisão da sua operação é " + str(res)

  return textoResposta

"""Parte do Código para interação com usuário"""

while True:
  print("Calculadora Infinita")
  print("\nEscolha o tipo de operação!!")
  operador = int(input("\n1: Soma \n2: Subtração \n3: Multiplicação \n4: Divisão \n0: Sair\nQual operação iremos realizar: "))

  if(operador == 0):
    print("\nObrigado por utilizar nossa Calculadora...")
    break
  elif(operador > 0) and (operador < 5):
    primeiroNumero = int(input("\nInforme o primeiro número da nossa operação: "))
    segundoNumero = int(input("\nInforme o segundo número da nossa operação: "))
    resposta = calculadora(primeiroNumero, segundoNumero, operador)
    print(resposta)
  else:
    print("\nEssa opção não existe")